name: Playwright Tests
on:
  push:
    branches: [ feature/develop2ts ]
  pull_request:
    branches: [ feature/develop2ts ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/2
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 30

  merge-reports:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true
      
      - name: Merge Playwright reports
        
        if: ${{ !cancelled() }}
        run: |
        mkdir -p ./all-blob-reports
        if [ -d "./all-blob-reports" ] && [ "$(ls -A ./all-blob-reports)" ]; then
        npx playwright merge-reports --reporter html ./all-blob-reports
    else
      echo "No blob reports found to merge."
    fi
  - name: Upload playwright combined report
    uses: actions/upload-artifact@v4
    with:
        name: html-report
        path: playwright-report
        retention-days: 30